import JSZip from "jszip";
import { downloadBlob } from "../../../shared/utils/files";
import type { RenderedPage } from "../types";

export const ensureFolderPermission = async (handle: FileSystemDirectoryHandle) => {
  const descriptor = { mode: "readwrite" as const };
  const query = await handle.queryPermission?.(descriptor);
  if (query === "granted") {
    return true;
  }

  const request = await handle.requestPermission?.(descriptor);
  return request === "granted";
};

export const savePagesToFolder = async (
  pages: RenderedPage[],
  handle: FileSystemDirectoryHandle
) => {
  const granted = await ensureFolderPermission(handle);
  if (!granted) {
    throw new Error("folderPermissionDenied");
  }

  let saved = 0;
  for (const page of pages) {
    const fileHandle = await handle.getFileHandle(page.fileName, { create: true });
    const writable = await fileHandle.createWritable();
    await writable.write(page.blob);
    await writable.close();
    saved += 1;
  }

  return saved;
};

export const downloadPagesAsZip = async (pages: RenderedPage[]) => {
  const zip = new JSZip();

  for (const page of pages) {
    zip.file(page.fileName, page.blob);
  }

  const blob = await zip.generateAsync({
    type: "blob",
    compression: "STORE",
    comment: "Generated by InvoiceForge"
  });

  downloadBlob(blob, `invoiceforge-png-${Date.now()}.zip`);
};
